/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../pages/__root'
import { Route as PrivacyRouteImport } from './../../pages/privacy'
import { Route as IndexRouteImport } from './../../pages/index'
import { Route as SettingsIndexRouteImport } from './../../pages/settings.index'
import { Route as LoginIndexRouteImport } from './../../pages/login.index'
import { Route as ExpensesIndexRouteImport } from './../../pages/expenses.index'
import { Route as SettingsAccountRouteImport } from './../../pages/settings.account'
import { Route as LoginServiceIndexRouteImport } from './../../pages/login.$service.index'
import { Route as ExpensesRetrospectiveIndexRouteImport } from './../../pages/expenses.retrospective.index'
import { Route as ExpensesNewIndexRouteImport } from './../../pages/expenses.new.index'
import { Route as ExpensesUidIndexRouteImport } from './../../pages/expenses.$uid.index'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesIndexRoute = ExpensesIndexRouteImport.update({
  id: '/expenses/',
  path: '/expenses/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/settings/account',
  path: '/settings/account',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginServiceIndexRoute = LoginServiceIndexRouteImport.update({
  id: '/login/$service/',
  path: '/login/$service/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRetrospectiveIndexRoute =
  ExpensesRetrospectiveIndexRouteImport.update({
    id: '/expenses/retrospective/',
    path: '/expenses/retrospective/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExpensesNewIndexRoute = ExpensesNewIndexRouteImport.update({
  id: '/expenses/new/',
  path: '/expenses/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesUidIndexRoute = ExpensesUidIndexRouteImport.update({
  id: '/expenses/$uid/',
  path: '/expenses/$uid/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/settings/account': typeof SettingsAccountRoute
  '/expenses/': typeof ExpensesIndexRoute
  '/login/': typeof LoginIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/expenses/$uid/': typeof ExpensesUidIndexRoute
  '/expenses/new/': typeof ExpensesNewIndexRoute
  '/expenses/retrospective/': typeof ExpensesRetrospectiveIndexRoute
  '/login/$service/': typeof LoginServiceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/settings/account': typeof SettingsAccountRoute
  '/expenses': typeof ExpensesIndexRoute
  '/login': typeof LoginIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/expenses/$uid': typeof ExpensesUidIndexRoute
  '/expenses/new': typeof ExpensesNewIndexRoute
  '/expenses/retrospective': typeof ExpensesRetrospectiveIndexRoute
  '/login/$service': typeof LoginServiceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/settings/account': typeof SettingsAccountRoute
  '/expenses/': typeof ExpensesIndexRoute
  '/login/': typeof LoginIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/expenses/$uid/': typeof ExpensesUidIndexRoute
  '/expenses/new/': typeof ExpensesNewIndexRoute
  '/expenses/retrospective/': typeof ExpensesRetrospectiveIndexRoute
  '/login/$service/': typeof LoginServiceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/settings/account'
    | '/expenses/'
    | '/login/'
    | '/settings/'
    | '/expenses/$uid/'
    | '/expenses/new/'
    | '/expenses/retrospective/'
    | '/login/$service/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/settings/account'
    | '/expenses'
    | '/login'
    | '/settings'
    | '/expenses/$uid'
    | '/expenses/new'
    | '/expenses/retrospective'
    | '/login/$service'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/settings/account'
    | '/expenses/'
    | '/login/'
    | '/settings/'
    | '/expenses/$uid/'
    | '/expenses/new/'
    | '/expenses/retrospective/'
    | '/login/$service/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  SettingsAccountRoute: typeof SettingsAccountRoute
  ExpensesIndexRoute: typeof ExpensesIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  ExpensesUidIndexRoute: typeof ExpensesUidIndexRoute
  ExpensesNewIndexRoute: typeof ExpensesNewIndexRoute
  ExpensesRetrospectiveIndexRoute: typeof ExpensesRetrospectiveIndexRoute
  LoginServiceIndexRoute: typeof LoginServiceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/': {
      id: '/expenses/'
      path: '/expenses'
      fullPath: '/expenses/'
      preLoaderRoute: typeof ExpensesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/$service/': {
      id: '/login/$service/'
      path: '/login/$service'
      fullPath: '/login/$service/'
      preLoaderRoute: typeof LoginServiceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/retrospective/': {
      id: '/expenses/retrospective/'
      path: '/expenses/retrospective'
      fullPath: '/expenses/retrospective/'
      preLoaderRoute: typeof ExpensesRetrospectiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/new/': {
      id: '/expenses/new/'
      path: '/expenses/new'
      fullPath: '/expenses/new/'
      preLoaderRoute: typeof ExpensesNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/$uid/': {
      id: '/expenses/$uid/'
      path: '/expenses/$uid'
      fullPath: '/expenses/$uid/'
      preLoaderRoute: typeof ExpensesUidIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  SettingsAccountRoute: SettingsAccountRoute,
  ExpensesIndexRoute: ExpensesIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  ExpensesUidIndexRoute: ExpensesUidIndexRoute,
  ExpensesNewIndexRoute: ExpensesNewIndexRoute,
  ExpensesRetrospectiveIndexRoute: ExpensesRetrospectiveIndexRoute,
  LoginServiceIndexRoute: LoginServiceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
